class NurError(Exception):
    pass


class EvalError(NurError):
    pass
